import type { BankTutorial } from '@/lib/bank-statements/types'

export const BANK_TUTORIALS: BankTutorial[] = [
  {
    id: 'itau',
    name: 'Itaú',
    shortName: 'Itaú',
    accent: '#ff7a00',
    iconUrl: 'https://play-lh.googleusercontent.com/gRcutACE4XkEHmxcbUdOehxpTbp_LjmwJ6qIEbqfD34oh9feTNhTnlDgf97HEZ9eGKY=w240-h480',
    iconSourceUrl: 'https://play.google.com/store/apps/details?id=com.itau',
    supportedImportFormats: ['ofx', 'csv'],
    preferredImportFormat: 'ofx',
    ofxAvailability: 'secondary',
    ofxReferenceUrl: 'https://ajuda.bling.com.br/hc/pt-br/articles/360051603794',
    ofxReferenceLabel: 'Bling: passo a passo OFX',
    ofxIntro: 'Como referência secundária, o artigo do Bling descreve um fluxo possível de OFX pelo internet banking do Itaú.',
    ofxSteps: [
      { title: 'Entre no internet banking do Itaú', detail: 'Acesse com agência, conta e senha pelo site.' },
      { title: 'Abra o menu e clique em Extrato', detail: 'No ambiente web, vá para a área de extrato da conta.' },
      { title: 'Escolha o período e salve em OFX', detail: 'Selecione o intervalo desejado, clique em "Salvar" e escolha "Salvar em OFX".' },
    ],
    tutorialTitle: 'Baixar o extrato no app Itaú',
    intro: 'Prefira o OFX pelo internet banking. Para CSV, exporte o extrato pelo internet banking e salve como arquivo CSV.',
    steps: [
      { title: 'Acesse o internet banking do Itaú', detail: 'Entre com agência, conta e senha pelo site.' },
      { title: 'Abra Conta Corrente > Extrato', detail: 'Acesse a área de extrato da conta corrente.' },
      { title: 'Selecione o período e exporte', detail: 'Escolha o intervalo desejado e use a opção de salvar/exportar o extrato. Prefira OFX; se disponível, CSV também é aceito.' },
    ],
    observations: [
      'Prefira OFX para maior confiabilidade na leitura dos lançamentos.',
      'As telas do banco podem mudar com o tempo.',
    ],
    referenceLinks: [
      { label: 'Itaú: como consultar meu extrato', url: 'https://www.itau.com.br/atendimento-itau/para-voce/conta-corrente/como-consultar-o-meu-extrato-itau-e-o-que-significam-as-siglas-do-extrato' },
    ],
    images: [],
    lastVerifiedAt: '2026-04-16',
    status: 'validated',
  },
  {
    id: 'c6',
    name: 'C6 Bank',
    shortName: 'C6',
    accent: '#111111',
    iconUrl: 'https://play-lh.googleusercontent.com/qYXhGgBxFLr5xgnv0AGhqW9v7tyedb_i5AVoebI6pow5pWPNZH1qEHnslmSHNkVpB-g=w240-h480',
    iconSourceUrl: 'https://play.google.com/store/apps/details?id=com.c6bank.app',
    supportedImportFormats: ['csv'],
    preferredImportFormat: 'csv',
    ofxAvailability: 'not_confirmed',
    tutorialTitle: 'Baixar o extrato CSV no app C6 Bank',
    intro: 'O C6 Bank envia o extrato por e-mail em PDF protegido por senha. Para importar aqui, use a exportação em CSV disponível no app.',
    steps: [
      { title: 'Abra o app C6 e clique em "Ver Extrato"', detail: 'Acesse o app do C6 Bank e na tela inicial, toque em "Ver extrato".' },
      { title: 'Exporte em CSV', detail: 'Toque em "Exportar extrato", escolha o período desejado e selecione o formato CSV (não PDF).' },
      { title: 'Salve o arquivo e importe aqui', detail: 'Aguarde o arquivo CSV ser gerado e use-o nesta tela.' },
    ],
    observations: [
      'O C6 envia PDFs protegidos por senha que não podem ser lidos automaticamente — use CSV.',
      'O limite máximo do C6 é de 180 dias por exportação.',
      'As telas do banco podem mudar com o tempo.',
    ],
    referenceLinks: [
      { label: 'C6 Bank: como exportar o extrato', url: 'https://www.c6bank.com.br/blog/como-receber-o-extrato-da-sua-conta-do-c6-bank-por-e-mail' },
    ],
    images: [],
    lastVerifiedAt: '2026-04-16',
    status: 'validated',
  },
  {
    id: 'santander',
    name: 'Santander',
    shortName: 'Santander',
    accent: '#ec0000',
    iconUrl: 'https://play-lh.googleusercontent.com/g_QDzrOlw8Belx8qb47fUu0MPL6AVFzDdbOz_NJZYQDNLveHYxwiUoe09Wvkxf-_548q=w240-h480',
    iconSourceUrl: 'https://play.google.com/store/apps/details?id=com.santander.app',
    supportedImportFormats: ['ofx', 'csv'],
    preferredImportFormat: 'ofx',
    ofxAvailability: 'secondary',
    ofxReferenceUrl: 'https://ajuda.bling.com.br/hc/pt-br/articles/360051603794',
    ofxReferenceLabel: 'Bling: passo a passo OFX',
    ofxIntro: 'Como referência secundária, o Bling documenta um caminho possível para exportar OFX pelo internet banking do Santander.',
    ofxSteps: [
      { title: 'Entre no Internet Banking do Santander', detail: 'Acesse o site com seu login e senha.' },
      { title: 'Abra Conta Corrente > Extrato Conta Corrente', detail: 'Entre na área de extrato da conta corrente.' },
      { title: 'Escolha o período e selecione "Money 2000 ou Superior"', detail: 'Esse caminho gera o arquivo OFX para download.' },
    ],
    tutorialTitle: 'Baixar o extrato no app Santander',
    intro: 'Prefira OFX pelo internet banking. Para CSV, exporte o extrato na área de conta corrente.',
    steps: [
      { title: 'Acesse o internet banking do Santander', detail: 'Entre com login e senha pelo site.' },
      { title: 'Abra Conta Corrente > Extrato', detail: 'Acesse a área de extrato e selecione o período desejado.' },
      { title: 'Exporte o arquivo', detail: 'Escolha OFX (preferencial) ou CSV para importar aqui.' },
    ],
    observations: [
      'Prefira OFX para maior confiabilidade.',
      'As telas do banco podem mudar com o tempo.',
    ],
    referenceLinks: [
      { label: 'Santander: Consultar Extrato', url: 'https://www.santander.com.br/blog/consulta-saldo-extrato-santander' },
    ],
    images: [],
    lastVerifiedAt: '2026-04-16',
    status: 'validated',
  },
  {
    id: 'banco_do_brasil',
    name: 'Banco do Brasil',
    shortName: 'BB',
    accent: '#f6c400',
    iconUrl: 'https://play-lh.googleusercontent.com/1-aNhsSPNqiVluwNGZar_7F5PbQ4u1zteuJ1jumnArhe8bfYHHaVwu4aVOF5-NAmLaA=w240-h480',
    iconSourceUrl: 'https://play.google.com/store/apps/details?id=br.com.bb.android',
    supportedImportFormats: ['ofx', 'csv'],
    preferredImportFormat: 'ofx',
    ofxAvailability: 'secondary',
    ofxReferenceUrl: 'https://ajuda.bling.com.br/hc/pt-br/articles/360051603794',
    ofxReferenceLabel: 'Bling: passo a passo OFX',
    ofxIntro: 'Como referência secundária, o artigo do Bling descreve exportação OFX pelo internet banking do Banco do Brasil.',
    ofxSteps: [
      { title: 'Entre no internet banking do Banco do Brasil', detail: 'Acesse o site com seu login e senha.' },
      { title: 'Abra Conta Corrente > Conta Corrente', detail: 'Entre na área de extrato da conta.' },
      { title: 'Escolha o período e clique em "Money 2000+ (ofx)"', detail: 'Esse caminho baixa o arquivo OFX.' },
    ],
    tutorialTitle: 'Baixar o extrato no internet banking do Banco do Brasil',
    intro: 'Prefira OFX. Para CSV, o Banco do Brasil oferece exportação em CSV pelo internet banking.',
    steps: [
      { title: 'Acesse o Internet Banking', detail: 'Acesse o internet banking do Banco do Brasil com seu login e senha.' },
      { title: 'Acesse o menu do extrato', detail: 'Clique em Conta Corrente > Conta Corrente > Consultar > Extrato.' },
      { title: 'Selecione o período e exporte', detail: 'Escolha o intervalo, selecione OFX ou CSV e confirme o download.' },
    ],
    observations: [
      'Prefira OFX para maior confiabilidade.',
      'As telas do banco podem mudar com o tempo.',
    ],
    referenceLinks: [
      { label: 'Banco do Brasil: como exportar o extrato', url: 'https://ajuda.contaazul.com/hc/pt-br/articles/37835476984973-Banco-do-Brasil-como-exportar-o-extrato-em-CSV' },
    ],
    images: [],
    lastVerifiedAt: '2026-04-16',
    status: 'validation',
  },
  {
    id: 'caixa',
    name: 'CAIXA',
    shortName: 'CAIXA',
    accent: '#0066b3',
    iconUrl: 'https://play-lh.googleusercontent.com/ubV0x2kGJIEe10shxuFnH9Cy21OgHARwVUZ89nyE0YOZN9c25ov_dyHdk1rMgbPvoDI=w240-h480-rw',
    iconSourceUrl: 'https://play.google.com/store/apps/details?id=br.com.gabba.Caixa&hl=pt_BR',
    supportedImportFormats: ['ofx', 'csv'],
    preferredImportFormat: 'ofx',
    ofxAvailability: 'secondary',
    ofxReferenceUrl: 'https://ajuda.bling.com.br/hc/pt-br/articles/360051603794',
    ofxReferenceLabel: 'Bling: passo a passo OFX',
    ofxIntro: 'Como referência secundária, o Bling mostra um fluxo de OFX no internet banking da CAIXA.',
    ofxSteps: [
      { title: 'Entre no internet banking da CAIXA', detail: 'Acesse o site com seu login e senha.' },
      { title: 'Abra Contas da empresa > Extrato por período', detail: 'No ambiente web, vá até a opção de extrato por período.' },
      { title: 'Escolha o período, selecione OFX e clique em Continuar', detail: 'Esse caminho baixa o arquivo OFX.' },
    ],
    tutorialTitle: 'Baixar o extrato no internet banking da CAIXA',
    intro: 'Prefira OFX. Para CSV, acesse o internet banking da CAIXA e exporte o extrato no formato CSV.',
    steps: [
      { title: 'Acesse o internet banking da CAIXA', detail: 'Entre com seu login e senha pelo site.' },
      { title: 'Abra a área de extratos', detail: 'Acesse Conta Corrente > Extrato ou caminho equivalente.' },
      { title: 'Selecione o período e exporte', detail: 'Escolha OFX (preferencial) ou CSV para usar nesta tela.' },
    ],
    observations: [
      'Tutorial em validação: o fluxo exato de CSV não foi confirmado por fonte pública oficial.',
      'As telas do banco podem mudar com o tempo.',
    ],
    referenceLinks: [
      { label: 'CAIXA: portal oficial', url: 'https://www.caixa.gov.br/' },
    ],
    images: [],
    lastVerifiedAt: '2026-04-16',
    status: 'validation',
  },
  {
    id: 'nubank',
    name: 'Nubank',
    shortName: 'Nu',
    accent: '#820ad1',
    iconUrl: 'https://play-lh.googleusercontent.com/NPkx0aiwABB31gBw_CuZO9Rwukhir-BwemxfNlAVjT6smwk6QgUbb3XrmsSSClfzk0dY=w240-h480',
    iconSourceUrl: 'https://play.google.com/store/apps/details?id=com.nu.production&hl=pt_BR',
    supportedImportFormats: ['ofx', 'csv'],
    preferredImportFormat: 'ofx',
    ofxAvailability: 'official',
    ofxReferenceUrl: 'https://comunidade.nubank.com.br/novidades/post/exporte-extratos-diretamente-de-sua-conta-nubank-pelo-app-rbRYnw8qndyPd2S',
    ofxReferenceLabel: 'Nubank: OFX no app',
    ofxIntro: 'A comunidade oficial do Nubank confirma exportação de extrato em OFX pelo próprio app.',
    ofxSteps: [
      { title: 'Abra o app Nubank e entre na área da conta', detail: 'Na tela inicial, acesse a conta do Nubank.' },
      { title: 'Abra "Exportar extrato"', detail: 'No menu de ações, arraste para a esquerda e toque em "Exportar extrato".' },
      { title: 'Escolha o mês e exporte em OFX', detail: 'Selecione o período desejado e exporte o arquivo no formato OFX.' },
    ],
    tutorialTitle: 'Exportar extrato no app Nubank',
    intro: 'O Nubank permite exportar o extrato diretamente pelo app em OFX (preferencial) ou CSV.',
    steps: [
      { title: 'Abra o app Nubank e acesse a conta', detail: 'Na página inicial, entre na área da conta do Nubank.' },
      { title: 'Selecione "Exportar Extrato"', detail: 'No menu de ações, arraste para a esquerda e vá em "Exportar Extrato".' },
      { title: 'Selecione o mês e o formato', detail: 'Escolha OFX para maior confiabilidade, ou CSV se preferir. O arquivo será enviado para o seu e-mail.' },
    ],
    observations: [
      'Prefira OFX para maior confiabilidade na leitura dos lançamentos.',
      'As telas do banco podem mudar com o tempo.',
    ],
    referenceLinks: [
      { label: 'Nubank: exportar extratos pelo app', url: 'https://comunidade.nubank.com.br/novidades/post/exporte-extratos-diretamente-de-sua-conta-nubank-pelo-app-rbRYnw8qndyPd2S' },
    ],
    images: [],
    lastVerifiedAt: '2026-04-16',
    status: 'validated',
  },
  {
    id: 'bradesco',
    name: 'Bradesco',
    shortName: 'Bradesco',
    accent: '#c41230',
    iconUrl: 'https://play-lh.googleusercontent.com/ReQEaxm44OuduIlJEVO_-xs9iZXSyRNdzGKrONYoLSgAdOzyhPKTb1xuuoPXK6tABm0=w240-h480',
    iconSourceUrl: 'https://play.google.com/store/apps/details?id=com.bradesco',
    supportedImportFormats: ['ofx', 'csv'],
    preferredImportFormat: 'ofx',
    ofxAvailability: 'official',
    ofxReferenceUrl: 'https://www.institucional.bradesco.com.br/simulador_bradesco_net_empresa/conteudo/perfil_corporate/extrato/conta-corrente_extrato-de-cheque-empresarial.asp',
    ofxReferenceLabel: 'Bradesco: OFX no ambiente web',
    ofxIntro: 'O domínio institucional do Bradesco expõe o fluxo de exportação OFX no ambiente web.',
    ofxSteps: [
      { title: 'Entre no internet banking do Bradesco', detail: 'Acesse o site com seu login e senha.' },
      { title: 'Abra Saldos e Extratos > Extrato Mensal / Por Período', detail: 'Entre na consulta do extrato do período desejado.' },
      { title: 'Busque o extrato e salve como OFX', detail: 'Depois de carregar o extrato, clique em "Salvar como arquivo" e escolha "OFX (Money 2000 em diante)".' },
    ],
    tutorialTitle: 'Exportar extrato no internet banking Bradesco',
    intro: 'O Bradesco oferece exportação OFX e CSV pelo internet banking. Prefira OFX.',
    steps: [
      { title: 'Entre no internet banking do Bradesco', detail: 'Acesse o site com seu login e senha.' },
      { title: 'Abra Saldos e Extratos > Extrato', detail: 'Selecione o período desejado.' },
      { title: 'Exporte o arquivo', detail: 'Salve como OFX (preferencial) ou CSV para importar aqui.' },
    ],
    observations: [
      'Prefira OFX para maior confiabilidade.',
      'As telas do banco podem mudar com o tempo.',
    ],
    referenceLinks: [
      { label: 'Bradesco: exportação de extrato', url: 'https://institucional.bradesco.com.br/simulador_bradesco_net_empresa/conteudo/perfil_corporate/extrato/exportar_extrato_arquivo.asp' },
    ],
    images: [],
    lastVerifiedAt: '2026-04-16',
    status: 'validation',
  },
  {
    id: 'inter',
    name: 'Inter',
    shortName: 'Inter',
    accent: '#ff7a00',
    iconUrl: 'https://play-lh.googleusercontent.com/GvBsmvf0foXr0_IF7nC7yxime14I1_Mq3AEZcTa2d-SYB-dqHNfB5YbFN9TC5fydIvs=w240-h480',
    iconSourceUrl: 'https://play.google.com/store/apps/details?id=br.com.intermedium',
    supportedImportFormats: ['ofx', 'csv'],
    preferredImportFormat: 'ofx',
    ofxAvailability: 'official',
    ofxReferenceUrl: 'https://ajuda.inter.co/conta-digital-pessoa-fisica-e-mei/como-acessar-o-extrato-da-conta-digital-pf-ou-mei/',
    ofxReferenceLabel: 'Inter: OFX oficial',
    ofxIntro: 'A central oficial do Inter confirma exportação do extrato em CSV e OFX.',
    ofxSteps: [
      { title: 'Abra o Super App Inter e toque em Saldo', detail: 'Acesse a área principal da conta.' },
      { title: 'Toque em Mostrar extrato', detail: 'Se necessário, aplique os filtros do período desejado.' },
      { title: 'Use a seta para baixo e envie em OFX', detail: 'Escolha OFX para receber o arquivo por e-mail.' },
    ],
    tutorialTitle: 'Baixar o extrato no Super App Inter',
    intro: 'A central de ajuda do Inter descreve o caminho para enviar o extrato em OFX ou CSV por e-mail.',
    steps: [
      { title: 'Abra o Super App Inter e toque em Saldo', detail: 'Acesse a área principal da conta.' },
      { title: 'Toque em Mostrar extrato', detail: 'Se desejar, aplique filtros de período, categoria e tipo de transação.' },
      { title: 'Use a seta para baixo no canto superior direito', detail: 'Selecione "Enviar por e-mail" e escolha OFX (preferencial) ou CSV.' },
    ],
    observations: [
      'Prefira OFX para maior confiabilidade.',
      'As telas do banco podem mudar com o tempo.',
    ],
    referenceLinks: [
      { label: 'Inter: como acessar e exportar o extrato', url: 'https://ajuda.inter.co/conta-digital-pessoa-fisica-e-mei/como-acessar-o-extrato-da-conta-digital-pf-ou-mei/' },
    ],
    images: [],
    lastVerifiedAt: '2026-04-16',
    status: 'validated',
  },
]

export const BANK_TUTORIALS_BY_ID = Object.fromEntries(BANK_TUTORIALS.map((item) => [item.id, item])) as Record<
  BankTutorial['id'],
  BankTutorial
>
