export type CategorySeed = {
  kind: 'income' | 'expense'
  name: string
  name_en?: string
  name_es?: string
  is_system: boolean
  icon?: string
  children?: Array<{
    name: string
    name_en?: string
    name_es?: string
  }>
}

export const FAMILY_CATEGORY_SEEDS: CategorySeed[] = [
  {
    kind: 'expense',
    name: 'Moradia',
    name_en: 'Housing',
    name_es: 'Vivienda',
    is_system: true,
    icon: 'House',
    children: [
      { name: 'Aluguel / Financiamento', name_en: 'Rent / Mortgage', name_es: 'Alquiler / Hipoteca' },
      { name: 'Condomínio', name_en: 'HOA Fees', name_es: 'Cuota de condominio' },
      { name: 'Energia', name_en: 'Electricity', name_es: 'Electricidad' },
      { name: 'Água', name_en: 'Water', name_es: 'Agua' },
      { name: 'Internet', name_en: 'Internet', name_es: 'Internet' },
      { name: 'Gás', name_en: 'Gas', name_es: 'Gas' },
      { name: 'Impostos sobre moradia', name_en: 'Property Taxes', name_es: 'Impuestos de vivienda' },
      { name: 'Celular', name_en: 'Phone', name_es: 'Celular' },
      { name: 'TV', name_en: 'TV', name_es: 'TV' },
    ],
  },
  {
    kind: 'expense',
    name: 'Alimentação',
    name_en: 'Food',
    name_es: 'Alimentación',
    is_system: true,
    icon: 'Utensils',
    children: [
      { name: 'Supermercado', name_en: 'Supermarket', name_es: 'Supermercado' },
      { name: 'Restaurante', name_en: 'Restaurant', name_es: 'Restaurante' },
      { name: 'Delivery', name_en: 'Delivery', name_es: 'Delivery' },
    ],
  },
  {
    kind: 'expense',
    name: 'Pets',
    name_en: 'Pets',
    name_es: 'Mascotas',
    is_system: true,
    icon: 'PawPrint',
    children: [
      { name: 'Ração', name_en: 'Pet Food', name_es: 'Comida para mascotas' },
      { name: 'Veterinário', name_en: 'Veterinarian', name_es: 'Veterinario' },
      { name: 'Itens diários', name_en: 'Daily Items', name_es: 'Artículos diarios' },
    ],
  },
  {
    kind: 'expense',
    name: 'Lazer',
    name_en: 'Leisure',
    name_es: 'Ocio',
    is_system: true,
    icon: 'Smile',
    children: [
      { name: 'Cinema', name_en: 'Movies', name_es: 'Cine' },
      { name: 'Passeios', name_en: 'Outings', name_es: 'Salidas' },
      { name: 'Eventos', name_en: 'Events', name_es: 'Eventos' },
      { name: 'Presentes/Festas', name_en: 'Gifts/Parties', name_es: 'Regalos/Fiestas' },
    ],
  },
  {
    kind: 'expense',
    name: 'Investimentos para casa',
    name_en: 'Home Investments',
    name_es: 'Inversiones para el hogar',
    is_system: true,
    icon: 'HousePlus',
    children: [
      { name: 'Móveis', name_en: 'Furniture', name_es: 'Muebles' },
      { name: 'Eletrodomésticos', name_en: 'Appliances', name_es: 'Electrodomésticos' },
      { name: 'Reformas', name_en: 'Renovations', name_es: 'Renovaciones' },
    ],
  },
  {
    kind: 'expense',
    name: 'Transporte',
    name_en: 'Transportation',
    name_es: 'Transporte',
    is_system: true,
    icon: 'Car',
    children: [
      { name: 'Combustível', name_en: 'Fuel', name_es: 'Combustible' },
      { name: 'Uber / Ônibus / Metrô', name_en: 'Uber / Bus / Subway', name_es: 'Uber / Autobús / Metro' },
      { name: 'Manutenção', name_en: 'Maintenance', name_es: 'Mantenimiento' },
      { name: 'Aluguel de veículos', name_en: 'Vehicle Rental', name_es: 'Alquiler de vehículos' },
      { name: 'Aluguel de bicicletas', name_en: 'Bike Rental', name_es: 'Alquiler de bicicletas' },
      { name: 'Estacionamentos', name_en: 'Parking', name_es: 'Estacionamientos' },
      { name: 'Pedágios e pagamentos no veículo', name_en: 'Tolls and Vehicle Payments', name_es: 'Peajes y pagos del vehículo' },
      { name: 'Taxas e impostos sobre veículos', name_en: 'Vehicle Taxes and Fees', name_es: 'Impuestos y tasas del vehículo' },
      { name: 'Multas de trânsito', name_en: 'Traffic Fines', name_es: 'Multas de tránsito' },
    ],
  },
  {
    kind: 'expense',
    name: 'Saúde',
    name_en: 'Health',
    name_es: 'Salud',
    is_system: true,
    icon: 'HeartPlus',
    children: [
      { name: 'Farmácia', name_en: 'Pharmacy', name_es: 'Farmacia' },
      { name: 'Consultas', name_en: 'Appointments', name_es: 'Consultas' },
      { name: 'Exames', name_en: 'Tests', name_es: 'Exámenes' },
      { name: 'Plano de Saúde', name_en: 'Health Insurance', name_es: 'Seguro médico' },
      { name: 'Dentista', name_en: 'Dentist', name_es: 'Dentista' },
      { name: 'Bem-estar', name_en: 'Wellness', name_es: 'Bienestar' },
      { name: 'Academia e centros de lazer', name_en: 'Gym and Leisure Centers', name_es: 'Gimnasio y centros de ocio' },
      { name: 'Prática de esportes', name_en: 'Sports Practice', name_es: 'Práctica de deportes' },
      { name: 'Ótica', name_en: 'Optician', name_es: 'Óptica' },
      { name: 'Hospitais, clínicas e laboratórios', name_en: 'Hospitals, Clinics and Labs', name_es: 'Hospitales, clínicas y laboratorios' },
      { name: 'Salão de beleza e estética', name_en: 'Beauty Salon and Aesthetics', name_es: 'Salón de belleza y estética' },
      { name: 'Cirurgias plásticas', name_en: 'Plastic Surgery', name_es: 'Cirugías plásticas' },
    ],
  },
  {
    kind: 'expense',
    name: 'Roupas',
    name_en: 'Clothing',
    name_es: 'Ropa',
    is_system: true,
    icon: 'Shirt',
    children: [
      { name: 'Roupas do dia a dia', name_en: 'Everyday Clothing', name_es: 'Ropa del día a día' },
      { name: 'Calçados', name_en: 'Shoes', name_es: 'Calzado' },
      { name: 'Acessórios', name_en: 'Accessories', name_es: 'Accesorios' },
    ],
  },
  {
    kind: 'expense',
    name: 'Assinaturas',
    name_en: 'Subscriptions',
    name_es: 'Suscripciones',
    is_system: true,
    icon: 'MonitorPlay',
    children: [
      { name: 'Streaming', name_en: 'Streaming', name_es: 'Streaming' },
      { name: 'Software', name_en: 'Software', name_es: 'Software' },
      { name: 'Academia', name_en: 'Gym', name_es: 'Gimnasio' },
    ],
  },
  {
    kind: 'expense',
    name: 'Educação',
    name_en: 'Education',
    name_es: 'Educación',
    is_system: true,
    icon: 'Book',
    children: [
      { name: 'Cursos', name_en: 'Courses', name_es: 'Cursos' },
      { name: 'Livros', name_en: 'Books', name_es: 'Libros' },
      { name: 'Mensalidades', name_en: 'Tuition', name_es: 'Mensualidades' },
      { name: 'Universidade', name_en: 'University', name_es: 'Universidad' },
      { name: 'Escola', name_en: 'School', name_es: 'Escuela' },
      { name: 'Creche', name_en: 'Daycare', name_es: 'Guardería' },
    ],
  },
  {
    kind: 'expense',
    name: 'Hobbies',
    name_en: 'Hobbies',
    name_es: 'Pasatiempos',
    is_system: true,
    icon: 'Guitar',
    children: [
      { name: 'Esportes', name_en: 'Sports', name_es: 'Deportes' },
      { name: 'Artesanato', name_en: 'Crafts', name_es: 'Artesanía' },
      { name: 'Games', name_en: 'Games', name_es: 'Videojuegos' },
    ],
  },
  {
    kind: 'expense',
    name: 'Compras',
    name_en: 'Shopping',
    name_es: 'Compras',
    is_system: true,
    icon: 'ShoppingBag',
    children: [
      { name: 'Compras online', name_en: 'Online Shopping', name_es: 'Compras en línea' },
      { name: 'Eletrônicos', name_en: 'Electronics', name_es: 'Electrónica' },
      { name: 'Artigos infantis', name_en: "Kids' Items", name_es: 'Artículos infantiles' },
      { name: 'Artigos esportivos', name_en: 'Sporting Goods', name_es: 'Artículos deportivos' },
      { name: 'Livraria', name_en: 'Bookstore', name_es: 'Librería' },
      { name: 'Papelaria', name_en: 'Stationery', name_es: 'Papelería' },
    ],
  },
  {
    kind: 'expense',
    name: 'Viagens',
    name_en: 'Travel',
    name_es: 'Viajes',
    is_system: true,
    icon: 'Plane',
    children: [
      { name: 'Aeroportos e cias. aéreas', name_en: 'Airports and Airlines', name_es: 'Aeropuertos y aerolíneas' },
      { name: 'Hospedagem', name_en: 'Lodging', name_es: 'Alojamiento' },
      { name: 'Programas de milhagem', name_en: 'Mileage Programs', name_es: 'Programas de millas' },
      { name: 'Passagem de ônibus', name_en: 'Bus Tickets', name_es: 'Pasajes de autobús' },
      { name: 'Bilhetes', name_en: 'Tickets', name_es: 'Boletos' },
    ],
  },
  {
    kind: 'expense',
    name: 'Impostos e taxas',
    name_en: 'Taxes and Fees',
    name_es: 'Impuestos y tasas',
    is_system: true,
    icon: 'Landmark',
    children: [
      { name: 'Impostos', name_en: 'Taxes', name_es: 'Impuestos' },
    ],
  },
  {
    kind: 'expense',
    name: 'Seguros',
    name_en: 'Insurance',
    name_es: 'Seguros',
    is_system: true,
    icon: 'Shield',
    children: [
      { name: 'Seguro de vida', name_en: 'Life Insurance', name_es: 'Seguro de vida' },
      { name: 'Seguro residencial', name_en: 'Home Insurance', name_es: 'Seguro del hogar' },
      { name: 'Seguro de veículos', name_en: 'Vehicle Insurance', name_es: 'Seguro de vehículos' },
    ],
  },
  { kind: 'expense', name: 'Outros', name_en: 'Other', name_es: 'Otros', is_system: true, icon: 'Receipt' },
  {
    kind: 'income',
    name: 'Salário',
    name_en: 'Salary',
    name_es: 'Salario',
    is_system: true,
    icon: 'Banknote',
    children: [
      { name: 'Salário fixo', name_en: 'Fixed Salary', name_es: 'Salario fijo' },
      { name: 'Bônus', name_en: 'Bonus', name_es: 'Bono' },
    ],
  },
  {
    kind: 'income',
    name: 'Vale Alimentação',
    name_en: 'Meal Allowance',
    name_es: 'Vale de comida',
    is_system: true,
    icon: 'WalletCards',
    children: [
      { name: 'Benefício mensal', name_en: 'Monthly Benefit', name_es: 'Beneficio mensual' },
    ],
  },
  {
    kind: 'income',
    name: 'Outras Receitas',
    name_en: 'Other Income',
    name_es: 'Otros ingresos',
    is_system: true,
    icon: 'BadgeDollarSign',
    children: [
      { name: 'Cashback', name_en: 'Cashback', name_es: 'Cashback' },
      { name: 'Renda não recorrente', name_en: 'Non-recurring Income', name_es: 'Ingreso no recurrente' },
    ],
  },
]
